# This workflow runs the database migration tool when a change is made in the 'database/' folder and pushed to the 'main' branch.

name: Apply Database Migrations

on:
  push:
    branches: [ "main" ]
    paths: [ "database/**" ]
  workflow_dispatch:
    inputs:
      what_if:
        description: Run in What-If mode, does not apply migrations
        type: boolean
        required: false
        default: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup Google Cloud SQL Proxy
      uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: ${{ secrets.SYNCVR_GOOGLE_SQL_ACCOUNT }}
        instance: syncvr-assignment-368113:europe-west4:syncvr-production

    - name: Apply migrations
      # use --host localhost since we are using a proxy
      run: >
        dotnet run
        --project ./database/src/SyncVR.Database/SyncVR.Database.csproj
        --host localhost
        --port ${{ secrets.DB_PORT }}
        --database ${{ secrets.DB_NAME }}
        --username ${{ secrets.DB_USER }}
        --password ${{ secrets.DB_PASSWORD }}
        ${{ github.event.inputs.what_if && '--what-if' || '' }}
